#!/bin/busybox sh

/bin/mount -t devtmpfs devtmpfs /dev

# TODO: check for the block device instead of arbitrary sleep
sleep 2

mount -t vfat /dev/mmcblk0p1 /boot
mount -t squashfs -o loop,ro /boot/rootfs.squashfs /mnt

mkdir /tmp/work
mkdir /tmp/upper
mkdir /tmp/merged
mount -t overlay overlay -o lowerdir=/mnt,upperdir=/tmp/upper,workdir=/tmp/work /tmp/merged

echo "switching real root"

# Dont' use 'switch_root' because it will try to clean up /tmp and break the overlay
exec chroot /tmp/merged /linuxrc