#!/bin/sh

set -e

start() {
    /bin/echo "Setting up drive"
    /bin/sh /opt/setup.sh

    /bin/echo "Starting multitool..."
    /usr/bin/multitool &
}

case "$1" in
    start)
        start
        ;;
    *)
        exit 1
esac

exit $?
