#!/bin/sh

set -e

start() {
    export MULTITOOL_BASE_MOUNT="/mnt/"
    export MULTITOOL_SCRIPTS_PATH="/opt/multitool_scripts/"

    #TODO: fix with popen flags?
    export LVM_SUPPRESS_FD_WARNINGS=1

    /bin/echo "Setting up drive"
    /bin/sh $MULTITOOL_SCRIPTS_PATH/setup.sh

    /bin/echo "Starting multitool..."
    /usr/bin/multitool &
}

case "$1" in
    start)
        start
        ;;
    *)
        exit 1
esac

exit $?
